[package]
description = "rspack builtin next app loader"
edition     = "2021"
license     = "MIT"
name        = "rspack_loader_next_app"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"

[dependencies]
async-recursion          = { workspace = true }
async-trait              = { workspace = true }
base64-simd              = { version = "0.8.0", features = ["alloc"] }
cow-utils                = { workspace = true }
futures                  = { workspace = true }
json                     = { workspace = true }
lazy-regex               = "3.4.1"
regex                    = { workspace = true }
rspack_ast               = { workspace = true }
rspack_cacheable         = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_loader_runner     = { workspace = true }
rspack_paths             = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_swc_plugin_import = { workspace = true }
rspack_util              = { workspace = true }
serde                    = { workspace = true, features = ["derive"] }
serde-querystring        = "0.2.0"
serde_json               = { workspace = true }
sugar_path               = { workspace = true }
tokio                    = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["rspack_plugin_javascript", "rspack_swc_plugin_import", "rspack_ast"]
