[package]
description = "rspack next flight client entry plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_next_flight_client_entry"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_collections = { workspace = true }
rspack_core        = { workspace = true }
rspack_error       = { workspace = true }
rspack_hook        = { workspace = true }
rspack_paths       = { workspace = true }
rspack_util        = { workspace = true }

async-trait              = { workspace = true }
derive_more              = { workspace = true }
form_urlencoded          = "1.2.1"
futures                  = { workspace = true }
indexmap                 = { workspace = true }
lazy-regex               = "3.4.1"
querystring              = { version = "1.1.0" }
regex                    = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rustc-hash               = { workspace = true }
serde                    = { workspace = true }
serde_json               = { workspace = true }
sugar_path               = { workspace = true }
tracing                  = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
