name: CI

on:
  merge_group:
    types: [ checks_requested ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "website/**"
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

jobs:

  test-linux:
    name: Test Linux
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: x86_64-unknown-linux-gnu
      runner: ${{ vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"' }}
      test: true
      bench: false



  test-wasm:
    name: Test WASM
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: wasm32-wasip1-threads
      profile: "ci"
      runner: ${{ vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"' }}
      test: false


  # TODO: enable it after self hosted runners are ready
  # pkg-preview:
  #   name: Pkg Preview
  #   needs:
  #     - test-linux
  #     - test-windows
  #     - cargo-deny
  #     - lint
  #     - rust_check
  #     - rust_test
  #   # after merged to main branch
  #   if: ${{ !failure() && github.event_name == 'push' }}
  #   uses: ./.github/workflows/preview-commit.yml
