name: ecosystem-ci trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch of the Ecosystem CI run'
        required: true
        default: 'main'

jobs:
  ecosystem_ci:
    name: Run Ecosystem CI
    runs-on: ubuntu-latest
    if: github.repository == 'web-infra-dev/rspack'
    steps:
      - id: get-pr-number
        uses: actions/github-script@v7
        name: Get PR Number
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const targetBranch = context.payload.inputs.branch;

            const pr = prs.find(pr => pr.head.ref === targetBranch);

            if(pr) {
              console.log(`Get PR info: ${pr.url}`)

              return {
                num: pr.number,
                branchName: pr.head.ref,
                repo: pr.head.repo.full_name
              }
            } else {
              console.log(`can't find PR for branch: ${targetBranch}`)
            }

      - id: create-comment
        name: Create Comment
        uses: actions/github-script@v7
        if: steps.get-pr-number.outputs.result
        with:
          result-encoding: string
          script: |
            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            const urlLink = `[Open](${url})`
            const prData = ${{ steps.get-pr-number.outputs.result }}

            const { data: comment } = await github.rest.issues.createComment({
              issue_number: prData.num,
              owner: 'web-infra-dev',
              repo: 'rspack',
              body: `⏳ Triggered ecosystem CI: ${urlLink}`
            })
            return comment.id

      - name: Run Ecosystem CI
        id: eco_ci
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        continue-on-error: true
        with:
          owner: "rspack-contrib"
          repo: "rspack-ecosystem-ci"
          workflow_file_name: "ecosystem-ci-from-pr.yml"
          github_token: ${{ secrets.REPO_RSPACK_ECO_CI_GITHUB_TOKEN }}
          ref: "main"
          client_payload: '{"branchName":"${{ github.event.inputs.branch }}","prNumber":"0","repo":"web-infra-dev/rspack","suite":"-","suiteRefType":"precoded","suiteRef":"precoded"}'
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - id: eco-ci-result
        uses: ./.github/actions/eco-ci-result
        name: Get CI Result
        with:
          workflow-output: ${{ toJson(steps.eco_ci.outputs) }}

      - id: update-comment
        uses: actions/github-script@v7
        if: steps.get-pr-number.outputs.result
        name: Update Comment
        with:
          script: |
            await github.rest.issues.updateComment({
              owner: 'web-infra-dev',
              repo: 'rspack',
              comment_id: ${{ steps.create-comment.outputs.result }},
              body: ${{ steps.eco-ci-result.outputs.result }}
            })
